// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiYFnXRdd2HjNZCC1RJjVH-6uh7LzJOyw',
    appId: '1:650829874163:web:58e9881a8b685e32d88886',
    messagingSenderId: '650829874163',
    projectId: 'midterm-ac098',
    authDomain: 'midterm-ac098.firebaseapp.com',
    storageBucket: 'midterm-ac098.firebasestorage.app',
    measurementId: 'G-VD7B835GJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXt9EZRlYwOXpBSzu_B2xtjXCCil3HpQ0',
    appId: '1:650829874163:android:b644295a86979346d88886',
    messagingSenderId: '650829874163',
    projectId: 'midterm-ac098',
    storageBucket: 'midterm-ac098.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOcktATzXfKA3Ihyk58glgcduKKEbgtAg',
    appId: '1:650829874163:ios:2428f855228c9d27d88886',
    messagingSenderId: '650829874163',
    projectId: 'midterm-ac098',
    storageBucket: 'midterm-ac098.firebasestorage.app',
    iosBundleId: 'com.example.midterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOcktATzXfKA3Ihyk58glgcduKKEbgtAg',
    appId: '1:650829874163:ios:2428f855228c9d27d88886',
    messagingSenderId: '650829874163',
    projectId: 'midterm-ac098',
    storageBucket: 'midterm-ac098.firebasestorage.app',
    iosBundleId: 'com.example.midterm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiYFnXRdd2HjNZCC1RJjVH-6uh7LzJOyw',
    appId: '1:650829874163:web:0b7e4455eb96a4c9d88886',
    messagingSenderId: '650829874163',
    projectId: 'midterm-ac098',
    authDomain: 'midterm-ac098.firebaseapp.com',
    storageBucket: 'midterm-ac098.firebasestorage.app',
    measurementId: 'G-YDPR58791Z',
  );
}
